version: "3.8"

services:
  # Ollama AI Service Only
  ollama:
    image: ollama/ollama:latest
    container_name: codementor-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_data:
